name: OpenSpeedTest
version: v2.0.5
slug: openspeedtest
description: Free & Open-Source HTML5 Network Performance Estimation Tool
panel_icon: "mdi:speedometer"
panel_title: SpeedTest
webui: http://[HOST]:[PORT:3000]
ingress: true
ingress_port: 3000
ingress_entry: /
panel_admin: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: openspeedtest/latest
init: false
ports:
  3000/tcp: 3000
  3001/tcp: null
ports_description:
  3000/tcp: HTTP
  3001/tcp: HTTPS
url: https://hub.docker.com/r/openspeedtest/latest


