name: "TWC-Manager"
description: "TWC Manager via RS485"
version: "1.3.2"
slug: "twc-manager"
init: false
uart: true
map:
 - "config:rw"
arch:
  - aarch64
  - amd64
ports:
  80/tcp: 81
  8080/tcp: 8081
ports_description:
  80/tcp: TWC Manager web interface
  8080/tcp: TWC Manager web interface
apparmor: true
watchdog: "tcp://[HOST]:8080"
options:
  serial:
   enabled: true
   device: "/dev/serial/by-id/usb-WCH.CN_USB_Quad_Serial_BD65F0ABCD-if00"
   baud: "115200"
  config:
   twc_ip: "10.0.0.0"
  debug_enabled: false
schema:
  serial:
   enabled: "bool"
   device: "str"
   baud: "str"
  config:
   twc_ip: "str"
  debug_enabled: "bool"